Repository Scorpions-Robotics/vision-2021, pull requests merged in 2021-11, with the labels that each got.

#7 Add color filtering option.
  images/HSV-map.png
  misc/calibration/find_hsv_range.py
  misc/functions/functions.py
  settings.ini.template
  vision.py
Labels: enhancement

#12 Fix networktables issue
  vision.py
Labels: bug

#13 Fix shell security issue. Fixes: #9
  misc/camera/set_camera.py
  misc/functions/functions.py
Labels: security
